version: '3'
services:
  # PHP service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sirterh-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - sirterh-network

  # Nginx service
  webserver:
    image: nginx:alpine
    container_name: sirterh-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - sirterh-network

  # PostgreSQL service
  db:
    image: postgres:14-alpine
    container_name: sirterh-db
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_DB: sirterh
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      SERVICE_NAME: postgres
    volumes:
      - sirterh-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sirterh-network

  # Node service for frontend
  frontend:
    image: node:18-alpine
    container_name: sirterh-frontend
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./frontend:/var/www
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    networks:
      - sirterh-network

# Networks
networks:
  sirterh-network:
    driver: bridge

# Volumes
volumes:
  sirterh-data:
    driver: local